ZOO/ZOO/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('ZOO_App.urls')),
    path('admin/', admin.site.urls),
]

ZOO/ZOO_App/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'ZOO_App'
urlpatterns = [
    path('', views.render_index, name='index'),
    path('login', views.render_login, name='login'),
    path('registar', views.render_register, name='registar'),
    path('logout', views.render_logout, name='logout'),
    path('about',views.render_about, name='about'),
    path('noticias',views.render_noticias, name='listagem_noticias'),
    path('noticia/<int:noticia_id>',views.render_detalhe_noticia, name='detalhe_noticia'),
    path('shop',views.render_shop, name='shop'),
    path('<int:produto_id>/render_produto',views.render_produto, name='produto'),
    path('addProductToCart',views.addProductToCart, name='addProductToCart'),
    path('getProductsInCart',views.getProductsInCart, name='getProductsInCart'),
    path('purchase',views.render_purchase, name='purchase'),
    path('finishPurchase',views.finishPurchase, name='finishPurchase'),
    path('emptyCart',views.emptyCart, name='emptyCart'),
    path('<int:produto_id>/deleteProductFromCart',views.deleteProductFromCart, name='deleteProductFromCart'),
    path('<int:produto_id>/takeProductFromCart',views.takeProductFromCart, name='takeProductFromCart'),
    path('<int:produto_id>/sumProductToCart',views.sumProductToCart, name='sumProductToCart'),
    path('precario',views.render_precario, name='precario'),
    path('informacao_pessoal',views.render_informacao_pessoal, name='informacao_pessoal'),
    path('alterar_password',views.render_alterar_password, name='alterar_password'),
    path('minhascompras',views.render_minhascompras, name='minhascompras'),
    path('addComentario/<int:noticia_id>',views.addComentario, name='addComentario'),
    path('bilheteCompra/<int:crianca>/<int:adulto>/<int:senior>', views.bilheteCompra, name='bilheteCompra'),
    path('noticia/<int:noticia_id>/adicionar_like', views.render_adicionar_like, name='adicionar_like'),
    path('noticia/<int:noticia_id>/remover_like', views.render_remover_like, name='remover_like'),
    path('createProduct',views.render_createProduct, name='createProduct'),
    path('deleteProduct/<int:produto_id>',views.render_deleteProduct, name='deleteProduct'),
    path('noticias/criarNoticia',views.render_criar_noticia, name='criar_noticia'),
    path('noticia/<int:noticia_id>/remover_noticia',views.render_remover_noticia, name='remover_noticia'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ZOO/ZOO_App/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Utilizador(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    data_nascimento = models.DateField()
    morada = models.CharField(max_length=100)
    numero_contribuinte = models.IntegerField()


class Produto(models.Model):
    designacao = models.CharField(max_length=50)
    preco = models.FloatField()
    categoria = models.CharField(max_length=50)
    imagem = models.FileField(upload_to="Products", null=True)
    descricao = models.CharField(max_length=100)
    ativo = models.BooleanField(default=True)


class Fatura(models.Model):
    data = models.DateTimeField()
    preco_total = models.FloatField()
    utilizador = models.ForeignKey(Utilizador, on_delete=models.DO_NOTHING)


class FaturaProduto_pk(models.Model):
    class Meta:
        unique_together = (('fatura', 'produto'),)

    fatura = models.ForeignKey(Fatura, on_delete=models.DO_NOTHING)
    produto = models.ForeignKey(Produto, on_delete=models.DO_NOTHING)
    quantidade = models.IntegerField(default=0)
    


class ProdutoCarinhoCompras_pk(models.Model):
    class Meta:
        unique_together = (('produto', 'utilizador'),)

    produto = models.ForeignKey(Produto, on_delete=models.DO_NOTHING)
    utilizador = models.ForeignKey(Utilizador, on_delete=models.DO_NOTHING)
    quantidade = models.IntegerField(default = 0)


class Bilhete(models.Model):

    intervalo_idade = models.CharField(max_length=50)
    preco = models.FloatField()


class BilheteUtilizador(models.Model):
    bilhete = models.ForeignKey(Bilhete, on_delete=models.DO_NOTHING)
    utilizador = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    data_compra = models.DateTimeField(default=datetime.now)
    quantidade = models.IntegerField()


class Donativo(models.Model):
    utilizador = models.ForeignKey(Utilizador, on_delete=models.DO_NOTHING)
    quantidade = models.FloatField()
    data = models.DateTimeField()


class Tag(models.Model):
    nome = models.CharField(max_length=20)
    descricao = models.CharField(max_length=100)


class Noticia(models.Model):
    imagem = models.FileField(upload_to="noticias", null=True)
    descricao = models.CharField(max_length=200)
    titulo = models.CharField(max_length=20)


class NoticiaTag_pk(models.Model):
    class Meta:
        unique_together = (('noticia', 'tag'),)

    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.DO_NOTHING)


class UtilizadorNoticia_pk(models.Model):
    class Meta:
        unique_together = (('utilizador', 'noticia'),)

    utilizador = models.ForeignKey(Utilizador, on_delete=models.DO_NOTHING)
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE)
    data = models.DateField(default= datetime.now)
    like = models.BooleanField(default=False)

class Comentario(models.Model):
    utilizador = models.ForeignKey(Utilizador, on_delete=models.DO_NOTHING)
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE)
    data = models.DateField(default= datetime.now)
    comentario = models.CharField(max_length=200)
    
  

class Especie(models.Model):
    VALORES_CLASSE = [
        ("MAM", "Mamífero"),
        ("REP", "Réptil"),
        ("INS", "Inseto"),
        ("ANF", "Anfíbio"),
        ("ARA", "Aracnídeo"),

    ]
    VALORES_ALIMENTACAO = [
        ("C", "Carnívoro"),
        ("O", "Omnívoro"),
        ("H", "Herbívoro"),
    ]
    VALORES_REGIAO = [
        ("1", "Europa"),
        ("2", "América do Norte"),
        ("3", "América do Sul"),
        ("4", "África"),
        ("5", "Ártico"),
        ("6", "Antártida"),
        ("7", "Austrália"),
        ("8", "Ásia"),
        ("9", "Oceano Pacífico"),
        ("10", "Oceano Atlântico"),
        ("11", "Oceano Ártico"),
        ("12", "Oceano Antártico"),
        ("13", "Oceano Índico"),
    ]
    VALORES_ATIVIDADE = [
        ("N", "Noturno"),
        ("D", "Diurno"),
        ("C", "Crepuscular"),
    ]
    VALORES_VIDA_SOCIAL = [
        ("C", "Casal"),
        ("S", "Solitário"),
        ("B", "Bando"),
    ]
    VALORES_REPRODUCAO = [
        ("O", "Ovípara"),
        ("V", "Vívipara"),
    ]
    nome_especie = models.CharField(max_length=50)
    classe = models.CharField(max_length=3, choices=VALORES_CLASSE)
    alimentacao = models.CharField(max_length=1, choices=VALORES_ALIMENTACAO)
    regiao = models.CharField(max_length=2, choices=VALORES_REGIAO)
    quantidade = models.IntegerField()
    peso = models.CharField(max_length=30)
    comprimento = models.CharField(max_length=30)
    altura = models.CharField(max_length=30)
    atividade = models.CharField(max_length=1, choices=VALORES_ATIVIDADE)
    vida_social = models.CharField(max_length=1, choices=VALORES_VIDA_SOCIAL)
    reproducao = models.CharField(max_length=1, choices=VALORES_REPRODUCAO)
    ameacada = models.IntegerField()

ZOO/ZOO_App/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.db import transaction
from django.utils import timezone
from django.conf import settings

from .models import *


# Create your views here.

def admin_check(user):
    return user.is_superuser

def not_logged_check(user):
    return not user.is_authenticated


def render_index(request):
    if request.user.is_authenticated:
        list = getProductsInCart(request)
        return render(request, 'ZOO_App/index.html', {'all' :list})
    return render(request, 'ZOO_App/index.html')


def render_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('ZOO_App:index'))
        else:
            return render(request, 'ZOO_App/login.html')
    return render(request, 'ZOO_App/login.html')


@user_passes_test(not_logged_check, login_url='/')
def render_register(request):
    if request.method == 'POST':
        if request.POST.get("password") == request.POST.get("password2"):
            if request.POST.get('username').strip() != '' and request.POST.get('email').strip() != '' and request.POST.get('password').strip() != '' and request.POST.get('first_name').strip() != '' and request.POST.get('last_name').strip() != '' and request.POST.get('address').strip() != '' and request.POST.get('TIN').strip() != '':
                user = User.objects.create_user(request.POST.get("username"), request.POST.get("email"), request.POST.get("password"))
                user.first_name = request.POST.get("first_name")
                user.last_name = request.POST.get("last_name")
                user.save()
                utilizador = Utilizador(user=user, data_nascimento=request.POST.get("birth_date"), morada=request.POST.get("address"), numero_contribuinte=request.POST.get("TIN"))
                utilizador.save()
                user = authenticate(username=request.POST.get("username"), password=request.POST.get("password"))
                login(request, user)
                return HttpResponseRedirect(reverse('ZOO_App:index'))
            else:
                return render(request, 'ZOO_App/registar.html', {'error_message_empty_fields': "Não pode haver campos vazios!"})
        else:
            return render(request, 'ZOO_App/registar.html', {'error_message_password': "Passwords não são iguais!"})
    else:
        return render(request, 'ZOO_App/registar.html')


@login_required(login_url='/')
def render_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('ZOO_App:login'))

def render_about(request):
    if request.user.is_authenticated:
        list = getProductsInCart(request)
        return render(request, 'ZOO_App/about.html', {'all' :list})
    return render(request, 'ZOO_App/about.html')


def render_noticias(request):
    lista_noticias = Noticia.objects.all()
    if request.user.is_authenticated:
        listcart = getProductsInCart(request)
        lista_noticias_user = []
        lista_tags_user = []
        lista_tags={}
        lista_noticias_recomendadas = []
        listCart = getProductsInCart(request)
        for item in UtilizadorNoticia_pk.objects.filter(utilizador=request.user.utilizador):
            lista_noticias_user = lista_noticias_user + [item.noticia]
            for item2 in NoticiaTag_pk.objects.filter(noticia=item.noticia):
                if lista_tags is not None:
                    if item2.tag.nome not in lista_tags:
                        lista_tags[item2.tag.nome] = 1
                else:
                    lista_tags[item2.tag.nome] = 1
        for item in NoticiaTag_pk.objects.all():
            if item.noticia not in lista_noticias_user and item.tag.nome in lista_tags.keys():
                lista_noticias_recomendadas = lista_noticias_recomendadas + [item.noticia]
        if len(lista_noticias_recomendadas) < 4:
            for item in lista_noticias:
                if item not in lista_noticias_user:
                    lista_noticias_recomendadas = lista_noticias_recomendadas + [item]
        lista_noticias_recomendadas = lista_noticias_recomendadas + list(lista_noticias)
        lista_noticias_recomendadas = lista_noticias_recomendadas[0:4]
        lista_noticias = list(lista_noticias)
        if "searchTerm" in request.POST:
            searchTerm = request.POST["searchTerm"]
            for item in lista_noticias.copy():
                if item.descricao.find(searchTerm) == -1 and item.titulo.find(searchTerm) == -1:
                    lista_noticias.remove(item)
            for item in lista_noticias_recomendadas.copy():
                if item.descricao.find(searchTerm) == -1 and item.titulo.find(searchTerm) == -1:
                    lista_noticias_recomendadas.remove(item)
        return render(request, 'ZOO_App/listagem_noticias.html',
                      {'noticias': lista_noticias, 'recomendadas': lista_noticias_recomendadas[0:4], 'all' :listcart})
    lista_noticias = list(lista_noticias)
    if "searchTerm" in request.POST:
        searchTerm = request.POST["searchTerm"]
        for item in lista_noticias.copy():
            if item.descricao.find(searchTerm) == -1 and item.titulo.find(searchTerm) == -1:
                lista_noticias.remove(item)
    return render(request, 'ZOO_App/listagem_noticias.html',
                  {'noticias': lista_noticias, 'all' :list})



def render_detalhe_noticia(request, noticia_id):
    noticia = get_object_or_404(Noticia, pk=noticia_id)
    comments = Comentario.objects.filter(noticia=noticia)
    like_amount = len(UtilizadorNoticia_pk.objects.filter(noticia=noticia, like=True))
    if request.user.is_authenticated:
        try:
            visualizacao = UtilizadorNoticia_pk.objects.get(utilizador=request.user.utilizador, noticia=noticia)
        except UtilizadorNoticia_pk.DoesNotExist:
            visualizacao = UtilizadorNoticia_pk(utilizador=request.user.utilizador, noticia=noticia)
        visualizacao.save()
        list = getProductsInCart(request)
        return render(request, 'ZOO_App/detalhe_noticia.html', {'noticia': noticia, "comments": comments, 'all' :list, "like": visualizacao.like, "like_amount": like_amount})
    return render(request, 'ZOO_App/detalhe_noticia.html', {'noticia': noticia, "comments": comments, "like_amount": like_amount})

def render_precario(request):
    bilhetes = Bilhete.objects.all()
    if request.user.is_authenticated:
        list = getProductsInCart(request)
        return render(request, 'ZOO_App/precario.html', {'bilhete_list' :bilhetes, 'all' :list})
    return render(request, 'ZOO_App/precario.html', {'bilhete_list' :bilhetes})

def render_shop(request):
    product_list = Produto.objects.filter(ativo=True)
    
    product_types=  []
    for product in product_list:
        if product.categoria not in product_types:
            product_types.append(product.categoria)

    if request.user.is_authenticated:
        list = getProductsInCart(request)
        context = {'product_list': product_list,'all' :list, "product_types": product_types
        }
        return render(request, 'ZOO_App/shop_archive.html', context)
    context = {'product_list': product_list, "product_types": product_types
    }
    return render(request, 'ZOO_App/shop_archive.html', context)

def render_produto(request, produto_id):
    produto = get_object_or_404(Produto, pk=produto_id)
    if produto.ativo==False:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/')) 
    if request.user.is_authenticated:
        list = getProductsInCart(request)
        return render(request, 'ZOO_App/product_info.html', {'produto': produto,'all' :list})
    return render(request, 'ZOO_App/product_info.html', {'produto': produto})

@login_required(login_url='/login')
def addProductToCart(request):
    if request.method == 'POST':
        try:
            produto_id = request.POST.get("produto_id")
            quantidade = request.POST.get("quantidade")
        except KeyError:
            return render(request, 'ZOO_App/shop_archive.html')
        #request.user.id
        if produto_id:
            produto = get_object_or_404(Produto, pk=produto_id)
            if produto.ativo==False:
                return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/')) 
            utilizador = get_object_or_404(Utilizador, user_id=request.user.id)
            try:
                pcc_pk = ProdutoCarinhoCompras_pk.objects.get(produto=produto, utilizador=utilizador)
            except ProdutoCarinhoCompras_pk.DoesNotExist:
                pcc_pk2 = ProdutoCarinhoCompras_pk(produto=produto, utilizador=utilizador, quantidade = quantidade)
                pcc_pk2.save()
                return HttpResponseRedirect(reverse('ZOO_App:shop'))
            #pcc_pk = get_object_or_404(ProdutoCarinhoCompras_pk, pk=questao_id)
            pcc_pk.quantidade+=int('0' + quantidade)
            pcc_pk.save()
            return HttpResponseRedirect(reverse('ZOO_App:shop'))
        else:
            print("Produto selecionado não existe")
    else:
        return render(request, 'ZOO_App/shop_archive.html')  


def auxGetProductsInCart(utilizador):
    pcc_pk = ProdutoCarinhoCompras_pk.objects.filter(utilizador=utilizador)
    list=[]
    for item in pcc_pk:
        if item.produto.ativo==False:
            continue
        list.append(item)
    return list  

def getProductsInCart(request):
    product_list = Produto.objects.all()

ZOO/ZOO_App/templates/ZOO_App/alterar_password.html
{%extends "./index.html"%} {% block conteudo %} {% load static %}

  <form
  action="{% url 'ZOO_App:alterar_password' %}"
  method="post"
  class="row w-100 mt-3 mb-3 justify-content-center"
>
  {% csrf_token %}
  <div class="col-2">
    <label for="old_password" class="form-label ms-1"
      >Palavra passe antiga:
    </label>
    <input class="form-control" type="password" name="old_password" required />
    <br />
    <label for="new_password" class="form-label ms-1"
      >Palavra passe nova:
    </label>
    <input class="form-control" type="password" name="new_password" required />
    <br />
    <label for="new_password2" class="form-label ms-1"
      >Confirmar palavra passe nova:
    </label>
    <input class="form-control" type="password" name="new_password2" required />
    <input
      type="submit"
      value="Efetuar Alteração"
      class="btn btn-danger mt-3"
    />
    {% if incorrect_password %}
    <div class="alert alert-danger" role="alert">{{incorrect_password}}</div>
    {% endif %}
  </div>
</form>

{% endblock %}

ZOO/ZOO_App/templates/ZOO_App/informacao_pessoal.html
{%extends "./index.html"%} {% block conteudo %} {% load static %}
<form
  action="{% url 'ZOO_App:informacao_pessoal' %}"
  method="post"
  class="row w-100 mt-3 justify-content-center"
>
  {% csrf_token %}
  <div class="col-2">
    <label for="first_name" class="form-label ms-1">Primeiro Nome: </label>
    <input
      class="form-control"
      type="text"
      name="first_name"
      value="{{ user.first_name }}"
      disabled
    />
    <br />
    <label for="last_name" class="form-label ms-1">Último Nome: </label>
    <input
      class="form-control"
      type="text"
      name="last_name"
      value="{{ user.last_name }}"
      disabled
    />
    <br />
    <label for="email" class="form-label ms-1">Email: </label>
    <input
      class="form-control"
      type="email"
      name="email"
      value="{{ user.email }}"
    />
    <br />
    <label for="birthday" class="form-label ms-1">Data de nascimento: </label>
    <input
      class="form-control"
      type="date"
      name="birthday"
      value="{{ utilizador.data_nascimento|date:'Y-m-d' }}"
      disabled
    />
    <br />
    <label for="address" class="form-label ms-1">Morada: </label>
    <input
      class="form-control"
      type="text"
      name="address"
      value="{{ utilizador.morada }}"
    />
    <br />
    <label for="TIN" class="form-label ms-1">Número de Contribuinte: </label>
    <input
      class="form-control"
      type="number"
      name="TIN"
      value="{{ utilizador.numero_contribuinte }}"
      disabled
    />
    <br />
    <label for="password" class="form-label ms-1">Password: </label>
    <input
      class="form-control"
      type="password"
      name="password"
      value="-----------"
      disabled
    />
    <div class="row mt-3">
      <div class="col-auto g-0 ms-1">
        <input
          type="submit"
          value="Efetuar Alterações"
          class="btn btn-secondary"
        />
        <a href="{% url 'ZOO_App:alterar_password' %}" class="btn btn-warning"
          >Alterar Password</a
        >
      </div>
    </div>
    {% if efective_password_change %}
    <div class="alert alert-success" role="alert">
      {{efective_password_change}}
    </div>
    {% endif %}
  </div>
</form>
{% endblock %}

ZOO/ZOO_App/templates/ZOO_App/listagem_noticias.html
{%extends "./index.html"%} {% block conteudo %} {% load static %}
<style>
  .form-control:focus {
    border-color: #6c757d;
    box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.075) inset,
      0px 0px 8px rgba(33, 37, 41, 0.5);
  }
  a:hover {
    text-decoration: none;
  }
</style>
<form
  class="row w-100 mt-3 justify-content-center"
  action="{% url 'ZOO_App:listagem_noticias' %}"
  method="post"
>
  {% csrf_token %}
  <div class="col-auto">
    <div class="input-group">
      <input
        type="text"
        name="searchTerm"
        placeholder="Pesquise por notícias"
        class="form-control"
      />
      <button type="submit" class="btn btn-outline-secondary">Pesquisar</button>
    </div>
  </div>
</form>
{% if recomendadas %}
<div class="container text-center">
  <div class="row justify-content-center">
    <div class="col">
      <p class="text-center fs-3 fw-bolder mt-2 d-inline-block">
        Algumas recomendações para si
      </p>
      {% if request.user.is_superuser %}
      <a
        href="{% url 'ZOO_App:criar_noticia'%}"
        class="btn btn-success btn-checkout ms-5 mb-2"
      >
        Criar Notícia</a
      >
      {% endif %}
    </div>
  </div>
</div>

<div class="row row-cols-sm-1 row-cols-md-2">
  {% for noticia in recomendadas %}
  <div class="col my-2">
    <div class="card">
      <img
        src="{{ noticia.imagem.url }}"
        class="card-img-top"
        alt="imagem da noticia"
      />
      <div class="card-body">
        <h5 class="card-title">{{noticia.titulo}}</h5>
        <a
          href="{% url 'ZOO_App:detalhe_noticia' noticia.id %}"
          class="btn btn-secondary"
          >Abrir Notícia</a
        >
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<hr class="mx-5 fs-3" style="color: blueviolet" />
{% endif %}
<div class="container text-center">
  <div class="row row-cols-md-4">
    {% for noticia in noticias %}
    <div class="col my-2">
      <div class="card">
        <img
          src="{{ noticia.imagem.url }}"
          class="card-img-top"
          alt="imagem da noticia"
        />
        <div class="card-body">
          <h5 class="card-title">{{noticia.titulo}}</h5>
          <a
            href="{% url 'ZOO_App:detalhe_noticia' noticia.id %}"
            class="btn btn-secondary"
            >Abrir Notícia</a
          >
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

ZOO/ZOO_App/templates/ZOO_App/purchase.html
{%extends "./index.html"%} 

{%block titulo%} Product {%endblock%}
{% load static %}

{%block head%}

<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>



{%endblock%}

{%block conteudo%}
<style>
    .cart-content{
        width: 80%;
        margin-left: 10%;
        margin-right: 10%;
    }
    .cart-titlep{
        margin-top: 20px;
    }


</style>


<div class="cartp">
    <h2 class="cart-titlep" style="text-align: center; margin-bottom: 30px;"> Shopping Cart</h2>
    <div class="cart-contentp" style="    width: 80%; margin-left: 10%; margin-right: 10%;">
        {%if all%}
            {% for item in all %}
            <div class="cart-boxp" style="margin-top: 30px;">
                <!--<img src="" alt="" class="cart-image">--> 
                    <div class="row">
                        <div class="col" >
                            <img src="{{ item.produto.imagem.url }}" alt="" style=" width: 60%; height: auto; margin-left: 20%; margin-right: 20%;" class="product-cart-imagep">
                        </div>
                        <div class="col">
                            <h2 class="product-cart-pricep mt-4">{{item.produto.preco}} €</h2>
                            <a href="{% url 'ZOO_App:takeProductFromCart' item.produto.id%}" class="btn btn-checkout d-inline-block">
                                <i class="bx bxs-minus-circle product-remove bx-md"></i>
                            </a> 
                            <h3 class="product-quantityp d-inline-block mt-4">Quantidade: {{item.quantidade}}</h3>
                            <a href="{% url 'ZOO_App:sumProductToCart' item.produto.id%}" class="btn  btn-checkout d-inline-block ">
                                <i class="bx bxs-plus-circle product-removep bx-md"></i>
                            </a> 
                            <br>
                            <a href="{% url 'ZOO_App:deleteProductFromCart' item.produto.id%}" class="btn btn-danger btn-checkout mt-4">
                                <i class="bx bxs-trash-alt product-removep"></i>
                            </a> 
                        </div>
                    </div>
            </div>
            {% endfor %}
       
        
        <div class="cart-totalp float-end">
            <h3 class="cart-total-titlep" style=" display:inline-block"> Total: </h3>
            <h3 class="cart-total-pricep" style=" display:inline-block"> </h3>
            <h3 class="cart-total-__" style=" display:inline-block"> €</h3>
            
        </div>
        {% endif %}
    </div>
    <br><br>
    <form action="{% url 'ZOO_App:finishPurchase'%}" class="ms-5 " method="POST">
        
  {% csrf_token %}

        {% if user.utilizador.morada %}

        <label for="address">Morada:</label>
        <input type="text" class="form-control w-25" value="{{user.utilizador.morada}}" readonly>

        {% else %}

        <label for="address">Morada</label>
        <input type="text" class="form-control w-25" value="" readonly>
        
        {% endif %}  
        {% if user.utilizador.numero_contribuinte %}

        <label for="cont" class="mt-5">Número de Contribuinte:</label>
        <input type="number" class="form-control w-25" value="{{user.utilizador.numero_contribuinte}}" readonly>

        {% else %}

        <label for="cont">Número de Contribuinte</label>
        <input type="number" class="form-control w-25"  value="" readonly>
              
        {% endif %}
        
        <br>
        <div class="row mt-3 mb-3 w-100">
            <div class="col-auto">
                <input type="submit" class="btn btn-success   justify-content-end" value="Finalizar Compra">
            </div>
            <div class="col-auto">
                <a href="{% url 'ZOO_App:emptyCart'%}" class="btn btn-danger btn-checkout">
                    Esvaziar Carrinho</a>
            </div>
        </div>
        
        
    </form>
    

    
</div>


<script>
    function sum() {
        const prices = document.getElementsByClassName("product-cart-pricep");
        const quantities = document.getElementsByClassName("product-quantityp");
        let sum=0;
        let aux="";
        for (let index = 0; index < prices.length; index++) {
            aux = prices[index].textContent.substring(0, prices[index].textContent.length-2);
            sum += parseFloat(aux) * parseFloat(quantities[index].textContent.split(": ")[1]); 
        }
        
        let string = sum.toString();
        if(string.includes(".")){
            let aux2 = string.split(".")
            if (aux2[1].length > 2){
              string = aux2[0] + "." + aux2[1].substring(0,2) + " €";
            }else if (aux2[1].length===1)
              string = aux2[0] + "." + aux2[1].substring(0,1) + "0 €";
          }else
            string = string + ".00 €"
                   
          return string;

    }
    document.getElementsByClassName("cart-total-pricep")[0].textContent=sum();
</script>
{%endblock%}